packages:
  - 'packages/*'
  - 'examples/*'

catalog:
  # React ecosystem
  react: ^19.1.0
  react-dom: ^19.1.0
  '@types/react': ^19.1.2
  '@types/react-dom': ^19.1.3

  # Web3 libraries
  viem: ^2.28.1
  wagmi: ^2.15.1
  ethers: ^6.13.7

  # React Query
  '@tanstack/react-query': ^5.74.11

  # TypeScript
  typescript: ^5.8.3
  '@types/node': ^20.17.32

  # Sequence packages
  0xsequence: ^2.3.38
  '@0xsequence/api': ^2.3.38
  '@0xsequence/auth': ^2.3.38
  '@0xsequence/core': ^2.3.38
  '@0xsequence/design-system': 2.1.11
  '@0xsequence/ethauth': ^1.0.0
  '@0xsequence/indexer': ^2.3.38
  '@0xsequence/marketplace': ^2.3.38
  '@0xsequence/metadata': ^2.3.38
  '@0xsequence/network': ^2.3.38
  '@0xsequence/provider': ^2.3.38
  '@0xsequence/utils': ^2.3.38
  '@0xsequence/waas': ^2.3.38

  # UI Libraries
  motion: ^12.9.2
  '@radix-ui/react-popover': ^1.1.11
  '@radix-ui/react-select': ^2.2.5

  # Utilities
  fuse.js: ^7.1.0
  clsx: ^2.1.1
  qrcode.react: ^4.2.0

  # Build Tools
  tailwindcss: ^4.1.11
  vite: ^5.4.19
  '@vitejs/plugin-react': ^4.4.1
  rimraf: ^5.0.10
  concurrently: ^9.1.2

minimumReleaseAge: 20160 # If you remove or change this, you will be fired
minimumReleaseAgeExclude:
- '@0xsequence/*'
- '@0xtrails/*'
- '0xtrails'
- '0xsequence'