export const LOCAL_STORAGE_PREFIX = '@kit'
export const LOCAL_STORAGE_PREFIX_SETTINGS = 'settings'
export const LOCAL_STORAGE_PREFIX_THEME = 'theme'
export const LOCAL_STORAGE_PREFIX_ETHAUTH_PROOF = 'ethAuthProof'
export const LOCAL_STORAGE_PREFIX_ETHAUTH_SETTINGS = 'ethAuthSettings'
export const LOCAL_STORAGE_PREFIX_PROJECT_ACCESS_KEY = 'projectAccessKey'
export const LOCAL_STORAGE_PREFIX_GOOGLE_CLIENT_ID = 'googleClientId'
export const LOCAL_STORAGE_PREFIX_GOOGLE_ID_TOKEN = 'googleClientId'
export const LOCAL_STORAGE_PREFIX_WAAS_SESSION_HASH = 'waasSessionHash'

export enum LocalStorageKey {
  Settings = `${LOCAL_STORAGE_PREFIX}.${LOCAL_STORAGE_PREFIX_SETTINGS}`,
  Theme = `${LOCAL_STORAGE_PREFIX}.${LOCAL_STORAGE_PREFIX_THEME}`,
  EthAuthProof = `${LOCAL_STORAGE_PREFIX}.${LOCAL_STORAGE_PREFIX_ETHAUTH_PROOF}`,
  EthAuthSettings = `${LOCAL_STORAGE_PREFIX}.${LOCAL_STORAGE_PREFIX_ETHAUTH_SETTINGS}`,
  ProjectAccessKey = `${LOCAL_STORAGE_PREFIX}.${LOCAL_STORAGE_PREFIX_PROJECT_ACCESS_KEY}`,
  GoogleClientID = `${LOCAL_STORAGE_PREFIX}.${LOCAL_STORAGE_PREFIX_GOOGLE_CLIENT_ID}`,
  GoogleIDToken = `${LOCAL_STORAGE_PREFIX}.${LOCAL_STORAGE_PREFIX_GOOGLE_ID_TOKEN}`,
  WaasSessionHash = `${LOCAL_STORAGE_PREFIX}.${LOCAL_STORAGE_PREFIX_WAAS_SESSION_HASH}`
}
